INSTITUTIONS = [
    ("University of Aberdeen", "Aberdeen", IONA),
    ("Aberystwyth University", "Aberystwyth", IONA),
    ("University of Adelaide", "Adelaide", Oceania),
    ("University of Alberta", "Alberta", NorthAmerica),
    ("American University of Afghanistan (AUAF)", "Am Afghanistan", MiddleEast),
    ("Asian University for Women", "Asian Women", SouthAsia),
    ("Assumption University", "Assumption", SouthEastAsia),
    ("University of Athens", "Athens", Europe),
    ("Bar Ilan University (BIU)", "Bar Ilan", MiddleEast),
    ("University of Bath", "Bath", IONA),
    ("Beijing University of Technology", "Beijing UT", NorthAsia),
    ("Bilkent University", "Bilkent", MiddleEast),
    ("University of Birmingham", "Birmingham", IONA),
    ("University of Botswana", "Botswana", Africa),
    ("Brandeis University", "Brandeis", NorthAmerica),
    ("Universitas Brawijaya", "Brawijaya", SouthEastAsia),
    ("University of Calabar", "Calabar", Africa),
    ("University of Canterbury", "Canterbury", Oceania),
    ("University of Cape Town (UCT)", "Cape Town", Africa),
    ("Pontificia Universidad Católica de Chile", "Católica Chile", LatinAmerica),
    ("China Agricultural University (CAU)", "China Agricultural", NorthAsia),
    ("Premier University Chittagong", "Chittagong", SouthAsia),
    ("Chulalongkorn University", "Chulalongkorn", SouthEastAsia),
    ("Chung Ang University (CAU)", "Chung Ang", NorthAsia),
    ("City University of Hong Kong", "City Hong Kong", NorthAsia),
    ("Clemson University", "Clemson", NorthAmerica),
    ("Colgate University", "Colgate", NorthAmerica),
    ("University of Colombo", "Colombo", SouthAsia),
    ("Universidad Cooperativa de Colombia", "Cooperativa Colombia", LatinAmerica),
    ("Copenhagen Business School (CBS)", "Copenhangen", Europe),
    ("De La Salle University (DLSU)", "De La Salle", SouthEastAsia),
    ("Universidad de Alcala de Henares", "Extremadura", Europe),
    ("Frankfurt University", "Frankfurt", Europe),
    ("Free State,  University of the", "Free State", Africa),
    ("Georgetown University Qatar", "Georgetown Qatar", MiddleEast),
    ("University of Ghana", "Ghana", Africa),
    ("Griffith College", "Griffith", IONA),
    ("University of Helsinki", "Helsinki", Europe),
    ("Hitotsubashi University", "Hitotsubashi", NorthAsia),
    ("University of Hong Kong (HKU)", "Hong Kong", NorthAsia),
    ("Indian Institute of Technology Guwahati (IIT Guwahati)", "IIT Guwahati", SouthAsia),
    ("International Islamic University Malaysia (IIUM)", "IIU Malaysia", SouthEastAsia),
    ("Institut Teknologi Bandung", "IT Bundang", SouthEastAsia),
    ("Instituto Tecnologico Autonomo de Mexico (ITAM)", "ITA Mexico", LatinAmerica),
    ("Kabul University", "Kabul", MiddleEast),
    ("Kathmandu University", "Kathmandu", NorthAsia),
    ("King's College London (KCL)", "King's London", IONA),
    ("University of Kitakyushu", "Kitakyushu", NorthAsia),
    ("Koc University", "Koc", MiddleEast),
    ("Korea University", "Korea", NorthAsia),
    ("Kuwait University", "Kuwait", MiddleEast),
    ("Lahore University of Management Sciences", "Lahore Management", SouthAsia),
    ("National University of Laos", "Laos", SouthEastAsia),
    ("Leiden University", "Leiden", Europe),
    ("National University of Lesotho", "Lesotho", Africa),
    ("Linkopings Universitet", "Linkopings", Europe),
    ("University of Ljubljana", "Ljubljana", Europe),
    ("University of Macau", "Macau", NorthAsia),
    ("Makerere University", "Makerere", Africa),
    ("University of Manitoba", "Manitoba", NorthAmerica),
    ("University of Mannheim", "Mannheim", Europe),
    ("McGill University", "McGill", NorthAmerica),
    ("University of Maryland,  College Park", "MD College Park", NorthAmerica),
    ("Moscow State University of International Relations (MGIMO)", "MGIMO", Europe),
    ("Middle East Technical University (METU)", "Middle East TU", MiddleEast),
    ("Molepolole College of Education", "Molepolole", Africa),
    ("Universite de Montreal", "Montreal", NorthAmerica),
    ("Morehouse College", "Morehouse", NorthAmerica),
    ("Moscow Institute of Physics and Technology (MIPT)", "Moscow IPT", Europe),
    ("University of Mostar", "Mostar", Europe),
    ("Muenster University", "Muenster", Europe),
    ("Multimedia University Melaka (MMUM)", "Multimedia", SouthEastAsia),
    ("University of Namibia", "Namibia", Africa),
    ("Nankai University", "Nankai", NorthAsia),
    ("Nanyang Technological University (NTU)", "Nanyang TU", SouthEastAsia),
    ("National Taiwan University (NTU)", "Natl Taiwan", NorthAsia),
    ("Nazarbayev University", "Nazarbayev", MiddleEast),
    ("University of New South Wales (UNSW)", "New South Wales", Oceania),
    ("National Institute of Technology Karnataka", "NIT Karnataka", SouthAsia),
    ("National Law School of India University (NLSIU)", "NLS India", SouthAsia),
    ("National Law University,  Delhi", "NLU Delhi", SouthAsia),
    ("Northern Caribbean University", "Northern Carribean", LatinAmerica),
    ("University of Oklahoma (OU)", "Oklahoma", NorthAmerica),
    ("Osaka University", "Osaka", NorthAsia),
    ("Universitas Padjadjaran", "Padjadjaran", SouthEastAsia),
    ("Patrick Henry College", "Patrick Henry", NorthAmerica),
    ("University of Pennsylvania", "Pennsylvania", NorthAmerica),
    ("University of Pretoria (TUKS)", "Pretoria", Africa),
    ("University of the Philippines - Los Banos (UPLB)", "Philippines Los Banos", SouthEastAsia),
    ("Universiti Putra Malaysia (UPM)", "Putra Malaysia", SouthEastAsia),
    ("University of Queensland", "Queensland", Oceania),
    ("Rajalakshmi Engineering College", "Rajalakshmi", SouthAsia),
    ("Institut d'études politiques de Paris", "Sciences Po", Europe),
    ("University of Sheffield", "Sheffield", IONA),
    ("Sogang University", "Sogang", NorthAsia),
    ("St Andrews", "St Andrews", IONA),
    ("University of St Gallen", "St Gallen", Europe),
    ("Stellenbosch University", "Stellenbosch", Africa),
    ("Stockholm University", "Stockholm", Europe),
    ("Sun-Yat-Sen University", "Sun Yat Sen", NorthAsia),
    ("Tel Aviv University", "Tel Aviv", MiddleEast),
    ("Universiti Malaysia Terengganu", "Terengganu", SouthEastAsia),
    ("Tianjin Foreign Studies Univerisity (TFSU)", "Tianjin FSU", NorthAsia),
    ("University of Twente", "Twente", Europe),
    ("United International University", "United Intl", SouthAsia),
    ("University of Technology Jamaica", "UT Jamaica", LatinAmerica),
    ("University of Technology Sydney (UTS)", "UT Sydney", Oceania),
    ("University of Victoria", "Victoria Canada", NorthAmerica),
    ("Victoria University of Wellington", "Victoria Wellington", Oceania),
    ("Debattierklub Wien (Vienna)", "Vienna", Europe),
    ("University of Warsaw", "Warsaw", Europe),
    ("University of Warwick", "Warwick", IONA),
    ("University of Western Australia (UWA)", "Western Australia", Oceania),
    ("University of Western Sydney (UWS)", "Western Sydney", Oceania),
    ("University of the Witwatersrand", "Witwatersrand", Africa),
    ("York University", "York", NorthAmerica),
    ("University of Zagreb", "Zagreb", Europe),
    ("University of Zimbabwe", "Zimbabwe", Africa),
]

PERSON_NAMES = [
    ("Scott Zabel", PersonMale),
    ("Garrett Allbritton", PersonMale),
    ("Harold Lambrecht", PersonMale),
    ("Gene Raff", PersonMale),
    ("Wayne Yin", PersonMale),
    ("Vicente Geier", PersonMale),
    ("Rod Bischof", PersonMale),
    ("Reginald Guyette", PersonMale),
    ("Randy Salzer", PersonMale),
    ("Grady Covarrubias", PersonMale),
    ("Shon Picone", PersonMale),
    ("Mary Leadbetter", PersonMale),
    ("Sherwood Vanderbilt", PersonMale),
    ("Kenny Domer", PersonMale),
    ("Jeremy Binder", PersonMale),
    ("Nickolas Gilland", PersonMale),
    ("Galen Mogensen", PersonMale),
    ("Fermin Boothe", PersonMale),
    ("Avery Glick", PersonMale),
    ("Darnell Ruddock", PersonMale),
    ("Barry Blauser", PersonMale),
    ("Lemuel Sugar", PersonMale),
    ("Gale Mccalley", PersonMale),
    ("Dion Cuthbert", PersonMale),
    ("Shane Waldrip", PersonMale),
    ("Lewis Lewellen", PersonMale),
    ("Andreas Mccleskey", PersonMale),
    ("Patrick Shaughnessy", PersonMale),
    ("Fabian Rapozo", PersonMale),
    ("Vernon Trump", PersonMale),
    ("Raymundo Mayoral", PersonMale),
    ("Dexter Rohrer", PersonMale),
    ("Kim Moench", PersonMale),
    ("Monroe Summitt", PersonMale),
    ("Irving Mattie", PersonMale),
    ("Brendon Maldanado", PersonMale),
    ("Beau Lacaze", PersonMale),
    ("Duncan Hippert", PersonMale),
    ("Fritz Youmans", PersonMale),
    ("Carlton Leatherwood", PersonMale),
    ("Ferdinand Orourke", PersonMale),
    ("Heriberto Roesner", PersonMale),
    ("Charles Mcmillian", PersonMale),
    ("Porter Atkinson", PersonMale),
    ("Louis Scheider", PersonMale),
    ("Terence Najera", PersonMale),
    ("Milo Klopfenstein", PersonMale),
    ("Bernard Dillion", PersonMale),
    ("Titus Schwartzberg", PersonMale),
    ("Alfonzo Pattee", PersonMale),
    ("Elroy Maza", PersonMale),
    ("Denny Wildt", PersonMale),
    ("Oscar Shinault", PersonMale),
    ("Winford Coriell", PersonMale),
    ("Lorenzo Jagger", PersonMale),
    ("Lance Stookey", PersonMale),
    ("Lyle Kinsel", PersonMale),
    ("Hoyt Dimas", PersonMale),
    ("Efrain Weitzman", PersonMale),
    ("Lucien Herndon", PersonMale),
    ("Tyrone Tsai", PersonMale),
    ("Jean Chau", PersonMale),
    ("Raymon Tropea", PersonMale),
    ("Emmett Gaspar", PersonMale),
    ("Elton Rase", PersonMale),
    ("Vince Godlewski", PersonMale),
    ("Keven Canterbury", PersonMale),
    ("Jarvis Yamanaka", PersonMale),
    ("Shaun Peete", PersonMale),
    ("Cleo Armistead", PersonMale),
    ("Christopher Wojtowicz", PersonMale),
    ("Nickolas Hunger", PersonMale),
    ("Earl Dorsett", PersonMale),
    ("Ben Porterfield", PersonMale),
    ("Josef Deming", PersonMale),
    ("Antoine Pavone", PersonMale),
    ("Lino Schrom", PersonMale),
    ("Jules Whorton", PersonMale),
    ("Jacinto Michelsen", PersonMale),
    ("Eloy Krach", PersonMale),
    ("Morgan Reichel", PersonMale),
    ("Wilford Patten", PersonMale),
    ("Jerrod Keister", PersonMale),
    ("Raleigh Kirschbaum", PersonMale),
    ("Alfonzo Glance", PersonMale),
    ("Stan Lockwood", PersonMale),
    ("Carlos Olmsted", PersonMale),
    ("Lacy Maugeri", PersonMale),
    ("Dudley Salsbury", PersonMale),
    ("Trenton Twine", PersonMale),
    ("Numbers Bourget", PersonMale),
    ("Walton Prevatte", PersonMale),
    ("Buford Franzen", PersonMale),
    ("Odis Adolph", PersonMale),
    ("Zachariah Follette", PersonMale),
    ("Reid Abrahamson", PersonMale),
    ("Fausto Steinhoff", PersonMale),
    ("Domingo Devera", PersonMale),
    ("Chris Woll", PersonMale),
    ("Adolph Swader", PersonMale),
    ("Bridget Hanford", PersonFemale),
    ("Leola Feher", PersonFemale),
    ("Bell Kenton", PersonFemale),
    ("Leatha Donahue", PersonFemale),
    ("Beula Sondag", PersonFemale),
    ("Junita Schoemaker", PersonFemale),
    ("Essie Arnott", PersonFemale),
    ("Bibi Manning", PersonFemale),
    ("Latoria Indelicato", PersonFemale),
    ("Renna Hoard", PersonFemale),
    ("Josephine Thayer", PersonFemale),
    ("Katrice Service", PersonFemale),
    ("Kacey Scovil", PersonFemale),
    ("Myrtie Howson", PersonFemale),
    ("Hsiu Padgett", PersonFemale),
    ("Frida Savory", PersonFemale),
    ("Gisele Valenzula", PersonFemale),
    ("Domonique Dull", PersonFemale),
    ("Priscila Gorgone", PersonFemale),
    ("Ricki Hurlbut", PersonFemale),
    ("Lise Flock", PersonFemale),
    ("Magdalena Tasker", PersonFemale),
    ("Nelida Hazlitt", PersonFemale),
    ("Catherine Ludwig", PersonFemale),
    ("Elicia Gregory", PersonFemale),
    ("Gaynell Giffen", PersonFemale),
    ("Yi Backes", PersonFemale),
    ("Salina Emond", PersonFemale),
    ("Kortney Butz", PersonFemale),
    ("Kimiko Peiffer", PersonFemale),
    ("Joelle Strand", PersonFemale),
    ("Mirian Carstarphen", PersonFemale),
    ("Noelia Matus", PersonFemale),
    ("Valda Kuehner", PersonFemale),
    ("Neda Mckechnie", PersonFemale),
    ("Retta Austria", PersonFemale),
    ("Mercedes Kovar", PersonFemale),
    ("Lizzie Oakland", PersonFemale),
    ("Noemi Colosimo", PersonFemale),
    ("Jesusita Querry", PersonFemale),
    ("Cristal Ruffner", PersonFemale),
    ("Yanira Cudjoe", PersonFemale),
    ("Deidra Akins", PersonFemale),
    ("Marth Coldren", PersonFemale),
    ("Beverly Linebarger", PersonFemale),
    ("Yuko Godbold", PersonFemale),
    ("Maryrose Ethier", PersonFemale),
    ("Hallie Higgenbotham", PersonFemale),
    ("Patsy Stroop", PersonFemale),
    ("Sindy Priolo", PersonFemale),
    ("Hang Casto", PersonFemale),
    ("Bethanie Faulk", PersonFemale),
    ("Celina Tesar", PersonFemale),
    ("Shiela Chai", PersonFemale),
    ("Lawanda Su", PersonFemale),
    ("Ranee Ruge", PersonFemale),
    ("Yasmin Aigner", PersonFemale),
    ("Sixta Mcmurtrie", PersonFemale),
    ("Kristyn Diebold", PersonFemale),
    ("Lakita Doyon", PersonFemale),
    ("Vita Warne", PersonFemale),
    ("Eugena Unsworth", PersonFemale),
    ("Pia Bramble", PersonFemale),
    ("Margot Cheyne", PersonFemale),
    ("Petronila Barefoot", PersonFemale),
    ("Natisha Ceron", PersonFemale),
    ("Ashli Justin", PersonFemale),
    ("Regena Mac", PersonFemale),
    ("Theola Vince", PersonFemale),
    ("Saran Sant", PersonFemale),
    ("Svetlana Zick", PersonFemale),
    ("Nichole Blakeley", PersonFemale),
    ("Melonie Wolter", PersonFemale),
    ("Shakita Beams", PersonFemale),
    ("Aileen Silas", PersonFemale),
    ("Marti Mcnickle", PersonFemale),
    ("Chastity Ezell", PersonFemale),
    ("Ardell Wiesen", PersonFemale),
    ("Denisha Tester", PersonFemale),
    ("Oda Yearta", PersonFemale),
    ("Cecilia Hanlin", PersonFemale),
    ("Adeline Buettner", PersonFemale),
    ("Helena Yerger", PersonFemale),
    ("Zelma Brush", PersonFemale),
    ("Lilla Heather", PersonFemale),
    ("Nichol Factor", PersonFemale),
    ("Ethelyn Robichaud", PersonFemale),
    ("Kara Palmore", PersonFemale),
    ("Ayana Mckamey", PersonFemale),
    ("Karri Leopard", PersonFemale),
    ("Kimbra Pressler", PersonFemale),
    ("Roxann Stingley", PersonFemale),
    ("Lola Borrego", PersonFemale),
    ("So Michell", PersonFemale),
    ("Vennie Schafer", PersonFemale),
    ("Danelle Callis", PersonFemale),
    ("Pamelia Nies", PersonFemale),
    ("Vikki Fiorenza", PersonFemale),
    ("Fern Clever", PersonFemale),
    ("Shaniqua Warkentin", PersonFemale),
]